@startuml

Class Main{
+static void main()

+Collections.sort: names
+names: Arraylist
+design: String [] = {-----------------}

}

Class Read_Write{

+reading(inout names: Arraylist):void

+writing(inout names, design: Arraylist, String):void

}

Main --> Read_Write
Read_Write-->Main
@enduml