@startuml

Class Main{
+main()
+name: String
+author: String
+Java File: String
+CCS File: String
}

Class Generator{
+Gen(name, author, Java File, CCS File: String, String, String, String): void
+website: File
+name_website: File
+f1: File
+J: File
+CS: File
}

Main --> Generator: (1) Pass the information to the \n method Gen of the Generator class.
Generator--> Print: (2) Print the values from the void \nfunction Gen


@enduml